### ISSUE TITLE
Milestone 1 Task List

### ISSUE THREAD

**Issue by lurkstalker** [stat545ubc-2023/collaborative-group18#12]
[Milestone 1](https://stat545.stat.ubc.ca/collaborative-project/milestone1/ )
- [x] Exercise 1: Getting Setup
- [x] Exercise 2: Markdown Formatting
- [x] Exercise 3: Merge one Pull Request per teammate
- [x] Exercise 4: GitHub Issues
- [x] Exercise 5: Teamwork Contract
- [x] Exercise 6: Troubleshooting document
- [x] Exercise 7: README file
- [x] Exercise 8: Submitting this Milestone
