### ISSUE TITLE
Milestone 2 Task List

### ISSUE THREAD

**Issue by lurkstalker** [stat545ubc-2023/collaborative-group18#15]
[Milestone2](https://stat545.stat.ubc.ca/collaborative-project/milestone2/)
- [x] Exercise 0: Merge one Pull Request per teammate
- [x] Exercise 1: Troubleshooting document [troubleshooting-2.Rmd document](https://raw.githubusercontent.com/UBC-STAT/stat545.stat.ubc.ca/master/content/collaborative-project/milestone2/troubleshooting-2.Rmd)
  - [x] Troubleshooting Exercise **01** by @brandonliu2 
  - [x] Troubleshooting Exercise **02-04** by @berkeucar 
  - [x] Troubleshooting Exercise **05** by @lurkstalker 
  - [x] Troubleshooting Exercise **06** by @jacquelineb174 
- [x] Exercise 2: README file and tidy submission
- [x] Exercise 3: Submitting this Milestone

**Comment by lurkstalker** [comment]
Troubleshooting Exercise 01 goes here: https://github.com/stat545ubc-2023/collaborative-group18/pull/14

**Comment by lurkstalker** [comment]
Troubleshooting Exercise 05 answer for now: (To keep a linear git history, I will make a PR when other Exercise work are ready)

**We can find the minimum height and mass within each species, ignoring the missing values:**
```
starWars %>%
  group_by(species) %>%
  summarise(across(c("height", "mass"), function(x) min(x, na.rm=TRUE)))
```

**Comment by brandonliu2** [comment]
> Troubleshooting Exercise 05 answer for now: (To keep a linear git history, I will make a PR when other Exercise work are ready)
> 
> **We can find the minimum height and mass within each species, ignoring the missing values:**
> 
> ```
> starWars %>%
>   group_by(species) %>%
>   summarise(across(c("height", "mass"), function(x) min(x, na.rm=TRUE)))
> ```

makes sense, good work!

**Comment by berkeucar** [comment]
Good work Tim thanks! I think I am done with mine as well! So, you can pull it without any collisions!
